frameworkVersion: ">=1.54.0 <2.0.0"

service: wallabag-serverless-bot

plugins:
    - serverless-webpack
    - serverless-offline

custom:
    webpack:
        includeModules: true
        packager: yarn
        packagerOptions:
            ignoreScripts: true

provider:
    name: aws
    runtime: nodejs12.x
    profile: default
    region: ${opt:region, 'eu-west-1'}
    environment:
        NAMESPACE: Site config
        # SecureString from SSM Parameters
        GITHUB_TOKEN: ${ssm:GITHUB_TOKEN~true}

functions:
    extension:
        handler: functions/extension.handler
        description: Validate file extensions
        events:
            -
                http:
                    path: webhook/extension
                    method: post
                    cors: true

    weblate:
        handler: functions/weblate.handler
        description: Auto label a PR create by Weblate
        events:
            -
                http:
                    path: webhook/weblate
                    method: post
                    cors: true
